//// IMPORT LIBRARY PACKAGES NEEDED BY YOUR PROGRAM
//// SOME CLASSES WITHIN A PACKAGE MAY BE RESTRICTED
//// DEFINE ANY CLASS AND METHOD NEEDED
//// CLASS BEGINS, THIS CLASS IS REQUIRED
//class GCD
//{
//    // METHOD SIGNATURE BEGINS, THIS METHOD IS REQUIRED
//    public int generalizedGCD(int num, int[] arr)
//    {
//        // WRITE YOUR CODE HERE
//    }
//    // METHOD SIGNATURE ENDS
//}